name: Daily Ticketmaster Price Check

on:
  schedule:
    - cron: "*/30 * * * *"      # 09:00 CDMX
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      # Debug: imprime entorno básico del runner
      - name: Print env
        run: |
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          echo "HOME: $HOME"
          which python3 || true
          python3 -V || true

      # Crea y activa venv con el Python del sistema
      - name: Create venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python -V
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # En macOS no hace falta --with-deps
          python -m playwright install chromium

      - name: Run checker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:  ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          source .venv/bin/activate
          python check_prices.py

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: |
            debug_*.png
            debug_*.html
            debug_*_text.txt
            trace_*.zip
            prices.json
          if-no-files-found: warn

      - name: Commit state (prices.json)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add prices.json
          git commit -m "Update prices state [skip ci]" || echo "No changes"
          git push
